swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Inventory Flask and REST
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

paths:
  /mysqldb:
    get:
      operationId: "mysqldb.CheckInventory"
      tags:
        - "Inventory"
      summary: "The inventory data structure supported by the server application"
      description: "Return items in Inventory"
      responses:
        200:
          description: "Successful read inventory operation"
          schema:
            type: "array"
            items:
              properties:
                iname:
                  type: "string"
                timestamp:
                  type: "string"
