swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

paths:
  /item:
    get:
      operationId: "item.read"
      tags:
        - "Item"
      summary: "The item data structure supported by the server application"
      description: "Read the list of items"
      responses:
        200:
          description: "Successful read item list operation"
          schema:
            type: "array"
            items:
              properties:
                iname:
                  type: "string"
                timestamp:
                  type: "string"